CREATE SCHEMA CHIRPER;

CREATE TABLE CHIRPER.USER_DETAILS(
   ID       INT PRIMARY KEY NOT NULL,
   USERNAME CHAR(50)        NOT NULL,
   EMAIL    CHAR(50)        NOT NULL,
   PASSWORD CHAR(512)       NOT NULL
);